version: '3.7'

services:
    db:
        container_name: postgres
        image: postgres:15.2
        restart: always
        environment:
            - POSTGRES_USER = ${POSTGRES_USER}
            - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
            - POSTGRES_DB = ${POSTGRES_DB}
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - backend

    backend:
        container_name: backend
        image: my-backend-image
        restart: always
        ports:
            - '5000:5000'
        volumes:
            - uploads:/app/uploads
        networks:
            - backend
        environment:
            - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

volumes:
    postgres_data:
    uploads:

networks: backend
